### ISSUE TITLE
Скласти інтро.

### ISSUE THREAD

**Issue by andrey-akimov** [rojer1989/Homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by brhuman** [comment]
- I went from a private in the Army of the United States to the most famous astronaut in the universe (Юра, прости)! In 2014 I spent six months on the International Space Station for ESA’s Blue Dot mission. I'm now back in space on my second mission called Horizons where I will take over as Station commander for Expedition 57. My mission is to pioneer the future in space exploration, scientific discovery and aeronautics research.

**Comment by andrey-akimov** [comment]
Oh, thank you!
