### ISSUE TITLE
Скласти блок контактної інформації.

### ISSUE THREAD

**Issue by andrey-akimov** [rojer1989/Homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by brhuman** [comment]
https://twitter.com/johnnysins
https://www.facebook.com/Official.page.Johnny.Sins
https://www.instagram.com/johnnysins
