### ISSUE TITLE
Скласти таймлайн.

### ISSUE THREAD

**Issue by andrey-akimov** [rojer1989/Homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by brhuman** [comment]
EXPERIANCE

1988
Aged 10 years I made my first rocket.

1999
Made my first flight as a pilot.

2006
After the medical university, I started to work as a doctor in James Madison hospital.

2008
I tried my hand at firefighting.

2010
I was the founder and CEO of a startup that was making micro drones.

2011
I left the position of CEO of my startup to realize my childhood dream: to become an astronaut.

2014
Went to outer space for the first time out of the International Space Station for ESA’s Blue Dot mission.

2018
I'm preparing to take over as Station commander for Expedition 57.


EDUCATION

1996
I entered the military academy of the air force to receive higher education and training. I chose the air forces to be closer to the sky.

2006
Master's Degree in Public Health and Tropical Medicine, Tulane University, United States of America.

2011
NASA training center.
