### ISSUE TITLE
Скласти додаткові інформаційні блоки.

### ISSUE THREAD

**Issue by andrey-akimov** [rojer1989/Homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by brhuman** [comment]
LANGUAGES 📕

ENGLISH

SKILLS 🧐

FLYING A PLANE FLYING A SPACESHIP ROCKET LAUNCHING FIGHTING A FIRE MANAGING TREATING A COLD COUNTING WRITING SINGING DRIVING HORSE RIDING

CHARACTER 💪

CHEERFUL COMMUNICATIVE CAREFUL OPTIMIST DIRECT SOCIABLE CALM AMBITIOUS COMPETITIVE CHARMING INTERESTING CONFIDENT DARING

LIKES 😃

MUSIC PARTIES HUMOR IMAGINATION GUNS STRAWBERRY DOGS CATS FITNESS JEWELRY SHAVED HEAD MEAT RACING RUNNING JUGGLING MONEY GIRLS SPORT CARS LUXURY

DISLIKES 😞

CHANSON ADVERTISING HOVERBOARDS FAT FOOD DENTISTS ALCOHOL DRUGS CIGARETTES REALITY-SHOWS FOOTBALL ARROGANCE QUEUES

FAVORITE MOVIES 📽

MIST ROCKNROLLA SNATCH BRUCE ALMIGHTY LIAR LIAR YES MAN EIGHT BELOW INCREDIBLES VENOM DEADPOOL

WANTS 🌠

GO TO MARS MAKE THE WORLD BETTER PET THE PENGUIN

**Comment by andrey-akimov** [comment]
Awesome!
